# .github/workflows/ci.yml

name: CI Pipeline                     
on:                                   
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:                                
  test:                               
    runs-on: ubuntu-latest

    services:                         
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install packages and build assets
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
            google-chrome-stable curl default-mysql-client libjemalloc2 libvips
          yarn install --frozen-lockfile
          yarn build:css
          yarn build:js
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create db:schema:load RAILS_ENV=test

      - name: Run Rails tests
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://127.0.0.1:3306
        run: bundle exec rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v3
        with:
          path: tmp/screenshots
          if-no-files-found: ignore
