# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            default-mysql-client libjemalloc2 libvips-dev wget gnupg unzip

      - name: Install Google Chrome & Chromedriver
        run: |
          # Chrome repo
          wget -qO - https://dl.google.com/linux/linux_signing_key.pub \
            | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y google-chrome-stable

          # 対応する Chromedriver を LATEST_RELEASE から動的取得
          CHROME_VER=$(google-chrome --version | grep -oP '\d+\.\d+' | head -1)
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VER})
          wget -qO /tmp/chromedriver.zip \
            "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Ruby gems & build assets
        run: |
          yarn install --frozen-lockfile
          yarn build:css
          yarn build:js
          bundle install --jobs 4 --retry 3

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run system tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test:system

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
