name: Fast Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Run Brakeman
        # --exit-on-warn フラグを外すことで、警告があっても exit code 0 のままに
        run: bundle exec brakeman

  lint:
    name: lint
    needs: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop --fail-level warning

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install -y default-mysql-client

      - name: Install gems & build assets
        run: |
          yarn install --frozen-lockfile
          bundle install --jobs 4 --retry 3

      - name: Prepare database
        run: bundle exec rails db:create db:schema:load

      - name: Run unit tests
        run: bundle exec rails test
