name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run Brakeman
        run: bundle exec brakeman

  lint:
    name: lint
    needs: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --fail-level warning

  test:
    name: test_without_db
    needs: lint
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run non-DB tests
        run: |
          # モデル／コントローラなどDBを必要とするテストを除外
          bundle exec rails test test/lib test/services test/jobs test/mailers
