name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby (with bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Brakeman & RuboCop
        run: |
          bundle exec brakeman
          bundle exec rubocop --fail-level warning

  test:
    needs: check
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby (with bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare & Test
        run: |
          sudo apt-get update && sudo apt-get install -y default-mysql-client
          # MySQLコンテナの起動待ち（必要ならsleepを調整）
          sleep 10
          bundle exec rails db:schema:load
          bundle exec rails test
