name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run Brakeman
        run: bundle exec brakeman

  lint:
    name: lint
    needs: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --fail-level warning

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run non-DB tests (pure Ruby, no Rails init)
        run: |
          set -euo pipefail
          dirs="test/lib test/services test/jobs test/mailers"
          files=""
          for d in $dirs; do
            if [ -d "$d" ]; then
              found=$(find "$d" -type f -name '*_test.rb' -print)
              if [ -n "$found" ]; then
                files="$files $found"
              fi
            fi
          done
          # 実行
          if [ -z "${files// /}" ]; then
            echo "No non-DB test files found; nothing to run."
            exit 0
          else
            # Bundler 環境で ruby を使って Rails を初期化せずに各ファイルをロードして実行
            bundle exec ruby -Itest -e "ARGV.each{|f| load f}" -- $files
          fi
