name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies & Chrome
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            curl default-mysql-client libjemalloc2 libvips-dev wget gnupg
          # Google Chrome のリポジトリ追加
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y google-chrome-stable
          yarn install --frozen-lockfile
          yarn build:css
          yarn build:js
          bundle install --jobs 4 --retry 3

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run Rails tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
