name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman

  lint:
    name: lint
    needs: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --fail-level warning

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
        options: >-
          --health-cmd="mysqladmin ping -h db -u root -ppassword --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y default-mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..15}; do
            mysqladmin ping -h db -u root -ppassword --silent && break
            echo "Waiting for MySQL ($i/15)…"
            sleep 2
          done

      - name: Prepare DB and run tests
        run: |
          # Rails 6.1+ なら db:prepare で create+schema:load を一発実行
          bundle exec rails db:prepare
          bundle exec rails test
